### ISSUE TITLE
ui windows todo

### ISSUE THREAD

**Issue by lythx** [lythx/trakman#140]
list of ui components to design and code: 
- [x] tmxinfo 
- [x] maplist (these 2 are a thing already just need to refactor a bit and change design)
- [x] player stats windows - things like topsums etc there probably will be a lot of them but these are very easy to do and also are kinda important cuz we have button linking to playerstats so thats a good thing to start with I think
- [x] detailed map info - i guess for that one we can display all info we have in memory along with tmx description and full ranking, and karma-over-time graph (ye this one is a bit difficult so maybe leave it for later)
- [x] banlist
- [x] blacklist
- [x] mutelist
- [x] guestlist (these 4 need to have functionality eg unban/change reason/change time etc so we need to come up with design for that)
- [x] donation widget below liverecs probably (?)
- [x] live cps on top of the screen probably or something idk how we make it look good with live finishes tbh xdd, maybe do two vertical lists like in nations fullspeed but with some styling
- [x] live finishes asdasd
- [ ] personal cps - replacement for the nadeo thing in bottom (can do it similar to nations fullspeed too but with better design)
- [x] player list - easy access ban/kick etc.. (only for op and above)
