### ISSUE TITLE
more admin commands todo

### ISSUE THREAD

**Issue by wsrvn** [lythx/trakman#77]
we should add more admin commands, likely including those already in xaseco for feature parity.
ill list them all here, with checkmark indicating completeness/redundancy.
commands exclusive to our project arent in this list of course.

- [x] help - display help for commands with privilege > 0
- [x] ssn/setservername - set server name
- [x] sc/setcomment - set server comment
- [x]  sp/setpwd - set server player password
- [x] ssp/setspecpwd - set server spectator password
- [x] srp/setrefpwd - set server referee password (unneeded IMO)
- [x] smp/setmaxplayers - set the max player amount
- [x] sms/setmaxspecs - set the max spectators amount
- [x] sgm/setgamemode - set the next gamemode
- [x] srm/setrefmode - set the referee mode (unneeded too)
- [x] skip/nm/next/nextmap - skip the current map
- [ ] ne/nextenv - skip to the next map with the same environment (irrelevant)
- [x] res - restart the current map
- [x] add - add map from tmx (works, maybe needs some tidying up)
- [x] al/addlocal - add map from local files
- [x] kick - kick a player
- [x] kg/kickghost - kick a ""ghost"" player (very few usecases)
- [x] ban - ban a player
- [x] unban - unban a player
- [x] banip - ban an ip address
- [x] unbanip - unban an ip address
- [x] bl/blacklist - blacklist a player
- [x] ubl/unblacklist - unblacklist a player
- [x] ag/addguest - add a player to the guestlist
- [x] rg/removeguest - remove a player from the guestlist
- [x] er/endround - end current round, in rounds based gamemodes
- [x] shuffle/shufflemaps - shuffle the current tracklist
- [x] rt/removetrack/et/erasetrack - remove a map
- [x] mute/ignore - mute a player
- [x] um/unmute/unignore - unmute a player
- [x] ad/addadmin - add a new admin
- [x] op/addop - add a new operator
- [x] removeadmin/removeop - remove admin/op - implemented better in privileges
- [x] #126
- [x] pr/prunerecords - delete all records
- [x] acdl - set acdl
- [x] disablerespawn - disable cp respawns
- [x] fso/forceshowopp - force show opponents
- [x] fp/forceplay - force spectator into play mode
- [x] fs/forcespec - force player into spec mode
- [x] coppers - check server coppers
- [x] pay - pay coppers to a player
- [ ] pm - send a pm to admins (maybe useless)
- [ ] pmlog - display admin pm log (see above)
- [x] call - execute a dedicated server method (shouldnt be painful)
- [x] sd/shutdown - shutdown the server
- [x] sda/shutdownall - //sd does what this is suppsoed to do

these commands will need voting system to work first:
- [x] pv/passvote/pass - pass a vote (will be implemented after votes)
- [x] cv/cancelvote/cancel - cancel a vote

these commands will need the queue/jukebox system to work first:
- [x] prev - go back to the previous map (will only be implemented after/with the queue)
- [x] replay - requeue the current map
- [x] dq/dropqueue/djb/dropjukebox - drop specific map from the queue
- [x] cq/clearqueue/cjb/clearjukebox - clear the queue
- [x] ch/clearhistory - clear track history file (used to stop you from enqueuing a recent map)

these commands will need the ui system to work first:
- [x] warn - warn a player
- [x] players - display list of known players
- [x] dbll/displayblacklist/listblacks - display current blacklist
- [x] dbl/displaybanlist/listbans - display current ban list
- [x] dgl/displayguestlist/listguests - display current guestlist
- [x] dbil/displaybannediplist/listips - display banned ips list
- [x] dml/displaymutelist/listmutes - display current mute list
- [x] dmal/displaymasteradminlist/listmasters - display masteradmins list
- [x] dal/displayadminlist/listadmins - display admin list
- [x] dol/displayoperatorlist/listops - display operators list
- [x] wall/mta - display a message for everyone
- [ ] dc/disablechat - disable chat for a player (custom ui ml)
- [ ] ec/enablechat - enable chat for a player (custom ui ml)
